/// Conformance tests - verify Rust implementation matches Haskell lsm-tree
/// 
/// Test cases are generated by the Haskell conformance-generator program
/// and stored as JSON files. This test harness runs them and compares results.

use cardano_lsm::{LsmTree, LsmConfig, LsmSnapshot, Key, Value};
use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
enum Operation {
    Insert { 
        #[serde(with = "base64_serde")]
        key: Vec<u8>, 
        #[serde(with = "base64_serde")]
        value: Vec<u8> 
    },
    Get { 
        #[serde(with = "base64_serde")]
        key: Vec<u8> 
    },
    Delete { 
        #[serde(with = "base64_serde")]
        key: Vec<u8> 
    },
    Range { 
        #[serde(with = "base64_serde")]
        from: Vec<u8>, 
        #[serde(with = "base64_serde")]
        to: Vec<u8> 
    },
    Snapshot { 
        id: String 
    },
    Rollback { 
        snapshot_id: String 
    },
    Compact,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(untagged)]
enum OperationResult {
    Ok { #[serde(rename = "Ok")] value: Option<String> },
    OkRange { #[serde(rename = "OkRange")] pairs: Vec<(String, String)> },
    OkUnit { #[serde(rename = "OkUnit")] unit: Option<()> },
    Err { #[serde(rename = "Err")] message: String },
}

// Custom Deserialize to handle Haskell's format: {"OkUnit": null}, {"Ok": "..."}, etc.
impl<'de> Deserialize<'de> for OperationResult {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        use serde_json::Value;
        let value = Value::deserialize(deserializer)?;
        
        // Handle null at top level (shouldn't happen but let's be safe)
        if value.is_null() {
            return Err(serde::de::Error::custom("Got null instead of OperationResult object"));
        }
        
        if let Some(obj) = value.as_object() {
            if let Some(ok_val) = obj.get("Ok") {
                let v = if ok_val.is_null() {
                    None
                } else {
                    Some(ok_val.as_str().ok_or_else(|| serde::de::Error::custom("Ok value not a string"))?.to_string())
                };
                return Ok(OperationResult::Ok { value: v });
            }
            
            if let Some(range_val) = obj.get("OkRange") {
                let pairs: Vec<(String, String)> = serde_json::from_value(range_val.clone())
                    .map_err(serde::de::Error::custom)?;
                return Ok(OperationResult::OkRange { pairs });
            }
            
            if obj.contains_key("OkUnit") {
                return Ok(OperationResult::OkUnit { unit: None });
            }
            
            if let Some(err_val) = obj.get("Err") {
                let msg = err_val.as_str().ok_or_else(|| serde::de::Error::custom("Err not a string"))?.to_string();
                return Ok(OperationResult::Err { message: msg });
            }
            
            // Debug: show what we got
            let keys: Vec<_> = obj.keys().collect();
            return Err(serde::de::Error::custom(format!("Unknown object with keys: {:?}", keys)));
        }
        
        Err(serde::de::Error::custom(format!("Expected object, got: {:?}", value)))
    }
}

#[derive(Debug, Serialize, Deserialize)]
struct TestCase {
    version: String,
    seed: u64,
    config: TestConfig,
    operations: Vec<Operation>,
}

#[derive(Debug, Serialize, Deserialize)]
struct TestConfig {
    memtable_size: usize,
    bloom_bits_per_key: usize,
    #[serde(default = "default_compaction_trigger")]
    level0_compaction_trigger: usize,
}

fn default_compaction_trigger() -> usize { 4 }

#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct TestResults {
    results: Vec<OperationResult>,
}

// Helper module for base64 serde
mod base64_serde {
    use serde::{Deserialize, Deserializer, Serializer};
    use base64::prelude::*;
    
    pub fn serialize<S>(bytes: &Vec<u8>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&BASE64_STANDARD.encode(bytes))
    }
    
    pub fn deserialize<'de, D>(deserializer: D) -> Result<Vec<u8>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        BASE64_STANDARD.decode(&s).map_err(serde::de::Error::custom)
    }
}

fn run_conformance_test(test_case: &TestCase) -> TestResults {
    use base64::prelude::*;
    
    // Set up LSM config from test case
    let mut config = LsmConfig::default();
    config.memtable_size = test_case.config.memtable_size;
    config.bloom_filter_bits_per_key = test_case.config.bloom_bits_per_key;
    config.level0_compaction_trigger = test_case.config.level0_compaction_trigger;
    
    let temp_dir = tempfile::TempDir::new().unwrap();
    let mut tree = LsmTree::open(temp_dir.path(), config).unwrap();
    let mut snapshots: HashMap<String, LsmSnapshot> = HashMap::new();
    let mut results = Vec::new();
    
    for (_i, op) in test_case.operations.iter().enumerate() {
        let result = match op {
            Operation::Insert { key, value } => {
                match tree.insert(&Key::from(key), &Value::from(value)) {
                    Ok(_) => OperationResult::OkUnit { unit: None },
                    Err(e) => OperationResult::Err { message: format!("Insert failed: {}", e) },
                }
            }
            
            Operation::Get { key } => {
                match tree.get(&Key::from(key)) {
                    Ok(Some(v)) => OperationResult::Ok { value: Some(BASE64_STANDARD.encode(v.as_ref())) },
                    Ok(None) => OperationResult::Ok { value: None },
                    Err(e) => OperationResult::Err { message: format!("Get failed: {}", e) },
                }
            }
            
            Operation::Delete { key } => {
                match tree.delete(&Key::from(key)) {
                    Ok(_) => OperationResult::OkUnit { unit: None },
                    Err(e) => OperationResult::Err { message: format!("Delete failed: {}", e) },
                }
            }
            
            Operation::Range { from, to } => {
                let entries: Vec<_> = tree.range(&Key::from(from), &Key::from(to))
                    .map(|(k, v)| {
                        (BASE64_STANDARD.encode(k.as_ref()), BASE64_STANDARD.encode(v.as_ref()))
                    })
                    .collect();
                OperationResult::OkRange { pairs: entries }
            }
            
            Operation::Snapshot { id } => {
                let snap = tree.snapshot();
                snapshots.insert(id.clone(), snap);
                OperationResult::OkUnit { unit: None }
            }
            
            Operation::Rollback { snapshot_id } => {
                if let Some(snap) = snapshots.get(snapshot_id) {
                    match tree.rollback(snap.clone()) {
                        Ok(_) => OperationResult::OkUnit { unit: None },
                        Err(e) => OperationResult::Err { message: format!("Rollback failed: {}", e) },
                    }
                } else {
                    OperationResult::Err { message: "Snapshot not found".to_string() }
                }
            }
            
            Operation::Compact => {
                match tree.compact() {
                    Ok(_) => OperationResult::OkUnit { unit: None },
                    Err(e) => OperationResult::Err { message: format!("Compact failed: {}", e) },
                }
            }
        };
        
        results.push(result);
    }
    
    TestResults { results }
}

#[test]
fn test_conformance_suite() {
    let conformance_dir = Path::new("./conformance-tests");
    
    if !conformance_dir.exists() {
        eprintln!("⚠️  Conformance tests directory not found");
        eprintln!("    Run: just gen-conformance");
        eprintln!("    This will generate test cases using the Haskell lsm-tree");
        return;
    }
    
    let test_files = std::fs::read_dir(conformance_dir)
        .expect("Should be able to read conformance-tests directory");
    
    let mut passed = 0;
    let mut failed = 0;
    let mut skipped = 0;
    
    for entry in test_files {
        let entry = entry.unwrap();
        let path = entry.path();
        
        // Only process test case files (not .expected.json files)
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }
        
        let filename = path.file_name().unwrap().to_str().unwrap();
        if filename.contains("expected") {
            continue;
        }
        
        // Load test case
        let test_case_json = std::fs::read_to_string(&path).unwrap();
        let test_case: TestCase = match serde_json::from_str(&test_case_json) {
            Ok(tc) => tc,
            Err(e) => {
                eprintln!("❌ Failed to parse {}: {}", filename, e);
                failed += 1;
                continue;
            }
        };
        
        // Run test case
        let rust_results = run_conformance_test(&test_case);
        
        // Load expected results
        let expected_path = path.with_file_name(
            format!("{}.expected.json", path.file_stem().unwrap().to_str().unwrap())
        );
        
        if !expected_path.exists() {
            eprintln!("⚠️  Missing expected results for: {}", filename);
            skipped += 1;
            continue;
        }
        
        let expected_json = std::fs::read_to_string(&expected_path).unwrap();
        let expected: TestResults = match serde_json::from_str(&expected_json) {
            Ok(e) => e,
            Err(e) => {
                eprintln!("❌ Failed to parse expected results for {}: {}", filename, e);
                failed += 1;
                continue;
            }
        };
        
        // Compare results
        if rust_results.results == expected.results {
            passed += 1;
            eprintln!("✅ {}", filename);
        } else {
            failed += 1;
            eprintln!("❌ {}", filename);
            eprintln!("   Seed: {}", test_case.seed);
            eprintln!("   Operations: {}", test_case.operations.len());
            
            // Show first difference
            for (i, (rust, haskell)) in rust_results.results.iter()
                .zip(expected.results.iter())
                .enumerate() 
            {
                if rust != haskell {
                    eprintln!("   First difference at operation {}:", i);
                    eprintln!("     Expected: {:?}", haskell);
                    eprintln!("     Got:      {:?}", rust);
                    break;
                }
            }
        }
    }
    
    eprintln!("");
    eprintln!("📊 Conformance Test Results:");
    eprintln!("   ✅ Passed:  {}", passed);
    eprintln!("   ❌ Failed:  {}", failed);
    eprintln!("   ⚠️  Skipped: {}", skipped);
    
    assert_eq!(failed, 0, "{} conformance tests failed", failed);
}

#[cfg(test)]
mod manual_conformance {
    use super::*;
    
    /// Manual conformance test - simple insert/get sequence
    #[test]
    fn test_simple_insert_get_sequence() {
        let test_case = TestCase {
            version: "1.0".to_string(),
            seed: 42,
            config: TestConfig {
                memtable_size: 4096,
                bloom_bits_per_key: 10,
                level0_compaction_trigger: 4,
            },
            operations: vec![
                Operation::Insert { 
                    key: b"key1".to_vec(), 
                    value: b"value1".to_vec() 
                },
                Operation::Get { 
                    key: b"key1".to_vec() 
                },
                Operation::Insert { 
                    key: b"key2".to_vec(), 
                    value: b"value2".to_vec() 
                },
                Operation::Get { 
                    key: b"key1".to_vec() 
                },
                Operation::Get { 
                    key: b"key2".to_vec() 
                },
            ],
        };
        
        let results = run_conformance_test(&test_case);
        
        // Verify results
        use base64::prelude::*;
        assert_eq!(results.results[0], OperationResult::OkUnit { unit: None }); // Insert
        assert_eq!(results.results[1], OperationResult::Ok { value: Some(BASE64_STANDARD.encode(b"value1")) }); // Get key1
        assert_eq!(results.results[2], OperationResult::OkUnit { unit: None }); // Insert
        assert_eq!(results.results[3], OperationResult::Ok { value: Some(BASE64_STANDARD.encode(b"value1")) }); // Get key1
        assert_eq!(results.results[4], OperationResult::Ok { value: Some(BASE64_STANDARD.encode(b"value2")) }); // Get key2
    }
    
    /// Test delete and tombstone behavior
    #[test]
    fn test_delete_tombstone_sequence() {
        let test_case = TestCase {
            version: "1.0".to_string(),
            seed: 43,
            config: TestConfig {
                memtable_size: 4096,
                bloom_bits_per_key: 10,
                level0_compaction_trigger: 4,
            },
            operations: vec![
                Operation::Insert { key: b"key1".to_vec(), value: b"value1".to_vec() },
                Operation::Get { key: b"key1".to_vec() },
                Operation::Delete { key: b"key1".to_vec() },
                Operation::Get { key: b"key1".to_vec() },
            ],
        };
        
        let results = run_conformance_test(&test_case);
        
        use base64::prelude::*;
        assert_eq!(results.results[0], OperationResult::OkUnit { unit: None }); // Insert
        assert_eq!(results.results[1], OperationResult::Ok { value: Some(BASE64_STANDARD.encode(b"value1")) }); // Get - exists
        assert_eq!(results.results[2], OperationResult::OkUnit { unit: None }); // Delete
        assert_eq!(results.results[3], OperationResult::Ok { value: None }); // Get - deleted
    }
    
    /// Test snapshot and rollback
    #[test]
    fn test_snapshot_rollback_sequence() {
        let test_case = TestCase {
            version: "1.0".to_string(),
            seed: 44,
            config: TestConfig {
                memtable_size: 4096,
                bloom_bits_per_key: 10,
                level0_compaction_trigger: 4,
            },
            operations: vec![
                Operation::Insert { key: b"key1".to_vec(), value: b"value1".to_vec() },
                Operation::Snapshot { id: "snap1".to_string() },
                Operation::Insert { key: b"key2".to_vec(), value: b"value2".to_vec() },
                Operation::Get { key: b"key2".to_vec() },
                Operation::Rollback { snapshot_id: "snap1".to_string() },
                Operation::Get { key: b"key2".to_vec() }, // Should be gone after rollback
            ],
        };
        
        let results = run_conformance_test(&test_case);
        
        use base64::prelude::*;
        assert_eq!(results.results[5], OperationResult::Ok { value: None }); // key2 should be gone
    }
}
